HL7/crmi-ig

input/pages/using-cql.md
input/profiles/StructureDefinition-crmi-evaluationresultparameters.json

Applied all CQL-related changes, JIRA trackers in the commit messages

Br changes 2023 11 27

---

input/pages/content-lifecycle.md

https://jira.hl7.org/browse/FHIR-44001

FHIR-44001: Renamed bulleted entries

---

input/pages/content-lifecycle.md

https://jira.hl7.org/browse/FHIR-44000

FHIR-44000: Fixed sentence structure.

---

input/pages/introduction.md

https://jira.hl7.org/browse/FHIR-43769

FHIR-43769 & FHIR-43935: Figure descriptions 

---

input/pages/changes.md
input/pages/introduction.md

https://jira.hl7.org/browse/FHIR-43991 IG Capitalization

fix-ig-capitalization 

---

input/pages/naming-conventions.md

https://jira.hl7.org/browse/FHIR-43826

FHIR-43826: Added link to Terminology Expectations page

---

input/pages/artifact-repository-service.md

https://jira.hl7.org/browse/FHIR-44767

FHIR-44767: Authoring Artifact Repository Additions

---

input/pages/content-lifecycle.md

https://jira.hl7.org/browse/FHIR-44100

Incrementing version numbers resets version number to the right

---

input/pages/content-lifecycle.md

https://jira.hl7.org/browse/FHIR-44002

Draft version

---

input/pages/content-lifecycle.md

https://jira.hl7.org/browse/FHIR-43941

Clarify semver info

---

input/pages/naming-conventions.md

https://jira.hl7.org/browse/FHIR-43709

Name and title should be unique within canonical base

---

input/pages/artifact-terminology-service.md

https://jira.hl7.org/browse/FHIR-43716
https://jira.hl7.org/browse/FHIR-44728

State that versioning of manifests is an optional capability

---

input/pages/artifact-repository-service.md

https://jira.hl7.org/browse/FHIR-44766

FHIR-44766: Publishable Artifact Repository Additions

---

input/pages/introduction.md

Fix figure # reference

---

input/fsh/operation-definitions/release-operation.fsh
input/pages/artifact-lifecycle.md
input/pages/artifact-repository-service.md
input/pages/artifact-terminology-service.md
input/pages/operations.md

[FHIR-51019](https://jira.hl7.org/browse/FHIR-51019): Separated publication status from release management throughout

Separate publication from release status

---

input/fsh/operation-definitions/approve-operation.fsh

[FHIR-46634](https://jira.hl7.org/browse/FHIR-46634)
$approve id param cardinality

[FHIR-46634](https://jira.hl7.org/browse/FHIR-46634) $approve id param cardinality

---

input/fsh/extensions/crmi-license-extensions.fsh
input/fsh/operation-definitions/license-requirements-operation.fsh
input/pages/distribution.md

Initial work to support $license-requirements operation.

[FHIR-51555] license-requirements operation

---

input/fsh/operation-definitions/release-operation.fsh

[FHIR-48382](https://jira.hl7.org/browse/FHIR-48382)
$release param id cardinality

[FHIR-48382](https://jira.hl7.org/browse/FHIR-48382) $release param id cardinality

---

input/fsh/extensions/artifact-signature-extension.fsh
input/includes/menu.xml
input/pages/artifact-signing.md
oids.ini
sushi-config.yaml

Initial implementation details for artifact signing, and signature verification.

[FHIR-42586] implementation guidance for artifact signing.

---

input/fsh/operation-definitions/package-operation.fsh

[FHIR-46233](https://jira.hl7.org/browse/FHIR-46233)
wording of $package.terminologyEnpoint parameter

[FHIR-46233](https://jira.hl7.org/browse/FHIR-46233) wording of $package.terminologyEnpoint parameter

---

input/pages/packaging.md

[FHIR-46292](https://jira.hl7.org/browse/FHIR-46292)
Packaging uses "ifNotExist", but that should be "If-None-Exist"

[FHIR-46292](https://jira.hl7.org/browse/FHIR-46292) Packaging uses "ifNotExist", but that should be "If-None-Exist"

---

input/fsh/operation-definitions/artifact-diff-operation.fsh

[FHIR-46163](https://jira.hl7.org/browse/FHIR-46163)
Support terminology reference in $artifact-diff operation
Use semantics from $package #84

[FHIR-46163](https://jira.hl7.org/browse/FHIR-46163) Support terminology reference in $artifact-diff operation

---

input/pages/artifact-conventions.md

[FHIR-46395](https://jira.hl7.org/browse/FHIR-46395)
Title should be unique within resource type
Also addresses [FHIR-46396](https://jira.hl7.org/browse/FHIR-46396) Name and title should be unique within an IG

[FHIR-46395](https://jira.hl7.org/browse/FHIR-46395) Title should be unique within resource type

---

input/fsh/operation-definitions/approve-operation.fsh

[FHIR-46635](https://jira.hl7.org/browse/FHIR-46635)
$approve should include child artifacts

[FHIR-46635](https://jira.hl7.org/browse/FHIR-46635) $approve should include child artifacts
